### ISSUE TITLE
**Who I dared Review card**

### ISSUE THREAD

**Issue by schulztobi** [schulztobi/capstone-project#1]
As a user/creator of a dare
I want to have the option to review if the person i dared successfully completed my dare or not. Moreover I want to have the option to review the video/picture he/she/it did and after have the option to say yes or no.

**Description**

Page Layout tbd

**Acceptance Criteria**

- [ ]  user/creator has details info about his/her own created dare.
- [ ]  user/creator can review "evidence"(video/picture)
- [ ]  user/creator can evaluate the "evidence"
- [ ]  user/creator can confirm the dare is successul by pressing "You nailed it"
- [ ]  user/creator can decide the dare was unsuccesful by pressing "You fucked it"

**Tasks**
